### ISSUE TITLE
LLM 출력에 대한 Parsing Error

### ISSUE THREAD

**Issue by keytech42** [minggichae/COUrse#5]
10번 중에 1~2번 꼴로 parsing error가 발생한다~~고 한다~~.

**Comment by keytech42** [comment]
화이팅입니다!!💪

**Comment by minggichae** [comment]
해결 완료

문제점
1. api key 호출을 정상적으로 하지 못한 문제
2. 호출은 정상적으로 하였으나 답변을 저장하는 배열의 잘못된 선언으로 인한 문제
